### PR TITLE
Import styles from css file

### PR DESCRIPTION
**Pull request by usernamehw**
Screenshot (150)

Screenshot (151)

### CODE REVIEW

**Comment by usernamehw** [comment]
It could be optional (under a setting) if needed.

**Comment by usernamehw** [comment]
Do you just copy/paste style by hand from `styles.css` to `render.ts`? It was confusing when changing style didn't affect anything at the beginning.

**Comment by RandomFractals** [comment]
yeah, I could not get styles import to work. so, I kept it in styles.css and added a method in renderer to load them, duplicating them for now.

I would rather make cell borders optional. we'll have to add a setting for it, along with data table height described in #55

**Comment by usernamehw** [comment]
Ok, I don't know how to use vscode `getConfiguration` in renderer yet. 

Reverted the border change for now and changed style loading to use CSS from the file.

**Comment by RandomFractals** [comment]
@usernamehw so, notebook renderers do get some context info. I am not sure if it is extension context tho:

```
export const activate: ActivationFunction = context => {
```

Let's explore it more in #55 and I'll add an enhancement ticket for the cell borders (#59).

Thanks for that css import fix!

**Comment by usernamehw** [comment]
It looks like the same api as in webview:
```ts
context.postMessage
context.onDidReceiveMessage
```

**Comment by RandomFractals** [comment]
ok. we do have standard `extension.ts` too. I think we should wire settings there via custom `config.ts` like we did in our snippets viewer. 

actually, I forgot. we don't need ext. context for loading config. see: https://github.com/RandomFractals/vscode-snippets-viewer/blob/main/src/config.ts

**Pull request merged**
